name: 'Gomplate'
description: ''
inputs:
  file:
    default: ''
  out:
    default: ''
  context:
    default: ''
runs:
  using: 'docker'
  image: 'docker://docker.io/hairyhenderson/gomplate:v3.7.0@sha256:b622f5ab088b6c86b8d724701614646aadaec6b5e7ad6e0da00164fceca3c636'
  args:
    - '--file'
    - '${{ inputs.file }}'
    - '--out'
    - '${{ inputs.out }}'
    - '--context'
    - '${{ inputs.context }}'
