name: 'Gomplate'
description: ''
inputs:
  file:
    default: ''
  out:
    default: ''
  context:
    default: ''
runs:
  using: 'docker'
  image: 'docker://docker.io/hairyhenderson/gomplate:v3.11.0@sha256:794510e7c0fc6ae70070868f48602161c5dccc383bc9c3124706196e640806fe'
  args:
    - '--file'
    - '${{ inputs.file }}'
    - '--out'
    - '${{ inputs.out }}'
    - '--context'
    - '${{ inputs.context }}'
