name: 'Gomplate'
description: ''
inputs:
  file:
    default: ''
  out:
    default: ''
  context:
    default: ''
runs:
  using: 'docker'
  image: 'docker://docker.io/hairyhenderson/gomplate:v3.11.1@sha256:de0082bda2bb958c283fc66bca964a81dd16fef84b5eacdf1913f34801d8e38e'
  args:
    - '--file'
    - '${{ inputs.file }}'
    - '--out'
    - '${{ inputs.out }}'
    - '--context'
    - '${{ inputs.context }}'
