name: 'Gomplate'
description: ''
inputs:
  file:
    default: ''
  out:
    default: ''
  context:
    default: ''
runs:
  using: 'docker'
  image: 'docker://docker.io/hairyhenderson/gomplate:v3.11.7@sha256:4dea12abb24f1d6b4e27bc4a9db7353045808e65030172f16c8abd7e7ec2f198'
  args:
    - '--file'
    - '${{ inputs.file }}'
    - '--out'
    - '${{ inputs.out }}'
    - '--context'
    - '${{ inputs.context }}'
